use GitHub Actions
JuliaSmoothOptimizers/SuiteSparseMatrixCollection.jl pull request #10
Opened 2020-12-07 21:54 UTC by amontoison

2020-12-07 23:17 UTC, dpo commented
Wow. What's all that GenericLinearAlgebra junk? How is that getting pulled in?

I added keys to push the docs but it looks like it's complaining that `ssmc_matrices` has no docstring. It does though...

2020-12-07 23:19 UTC, dpo commented
You may be able to fix CirrusCI builds as in #9.

2020-12-08 17:13 UTC, amontoison commented
> Wow. What's all that GenericLinearAlgebra junk? How is that getting pulled in?

JuliaDB is the culprit.

> I added keys to push the docs but it looks like it's complaining that `ssmc_matrices` has no docstring. It does though...

We forgot to add it in ` docs/src/api.md`.

2020-12-08 17:58 UTC, dpo commented
Hmm. Windows failures say
```
tar: D\:\a\\SuiteSparseMatrixCollection.jl\\SuiteSparseMatrixCollection.jl\\src\\..\\data\\MM\\Oberwolfach: Cannot open: No such file or directory
103
tar: Error is not recoverable: exiting now
104
ERROR: LoadError: failed process: Process(`tar --force-local -zxf 'D:\a\SuiteSparseMatrixCollection.jl\SuiteSparseMatrixCollection.jl\src\..\data\MM\Oberwolfach\LF10.tar.gz' -C 'D:\a\SuiteSparseMatrixCollection.jl\SuiteSparseMatrixCollection.jl\src\..\data\MM\Oberwolfach'`, ProcessExited(2)) [2]
```
In the future, we'll have to use artifacts and get rid of JuliaDB...

In the meantime, maybe https://github.com/JuliaIO/Tar.jl ?

2020-12-09 05:42 UTC, amontoison commented
https://discourse.julialang.org/t/cross-platform-unpacking-of-tar-archive/31459
https://github.com/oxinabox/DataDeps.jl/blob/master/src/post_fetch_helpers.jl

It's also true for 7z...
![tar](https://user-images.githubusercontent.com/35051714/101589505-8f8ac700-39b6-11eb-90f5-eb57ee3d4a5b.png)

2020-12-09 14:55 UTC, dpo commented
This package is going to move artifacts + dataframes pretty soon...

2020-12-13 22:26 UTC, dpo requested changes
Rebase on top of #12 when it's merged.

2020-12-13 22:26 UTC, dpo commented on Project.toml
> +JuliaDB = "^0.13"
```suggestion
JuliaDB = "^0.12"
```
Let's not bother doing this. I have a PR to phase out JuliaDB.

2020-12-13 22:26 UTC, dpo commented on docs/Project.toml
> +JuliaDB = "^0.13"
```suggestion
JuliaDB = "^0.12"
```

2020-12-13 22:26 UTC, dpo commented on src/SuiteSparseMatrixCollection.jl
> +      end
Let's not do this either. It looks like it's the tar file that has some issues, not the tar command. I'll see if I can make those matrices available as artifacts instead.

2020-12-14 18:31 UTC, dpo commented
It turns out that the tarballs themselves are malformed. Tar.jl can't read them. So artifacts won't work either. What I suggest is that in the tests, if the system is Windows, we download the MAT format.

2020-12-14 22:28 UTC, dpo commented
Phew!!! Awesome, thank you!

2020-12-14 22:29 UTC, merged